<?php

namespace Database\Seeders;

use App\Enum\BaseinfoTypesEnum;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class BaseinfoTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::unprepared('SET FOREIGN_KEY_CHECKS=0;');
        DB::table('baseinfos')->where('id', '<=', 10000)->delete();
        DB::table('baseinfos')->insert([
            [
                'id' => 1,
                'type' => BaseinfoTypesEnum::DISCIPLINE->value,
                'value' => 'Discipline',
                'priority' => 0,
                'parent_id' => 0,
                'user_can_add' => 0,
                'user_can_view' => 1,
                'extra_value' => '',
            ],
            [
                'id' => 2,
                'type' => BaseinfoTypesEnum::DISCIPLINE->value,
                'value' => 'General',
                // 'value' => 'general',
                'priority' => 0,
                'parent_id' => 1,
                'user_can_add' => 0,
                'user_can_view' => 1,
                'extra_value' => '',
            ],
            [
                'id' => 3,
                'type' => BaseinfoTypesEnum::DISCIPLINE->value,
                'value' => 'Structure',
                // 'value' => 'سازه',
                'priority' => 0,
                'parent_id' => 1,
                'user_can_add' => 0,
                'user_can_view' => 1,
                'extra_value' => '',
            ],
            [
                'id' => 4,
                'type' => BaseinfoTypesEnum::DISCIPLINE->value,
                'value' => 'Installation',
                // 'value' => 'تاسیسات',
                'priority' => 0,
                'parent_id' => 1,
                'user_can_add' => 0,
                'user_can_view' => 1,
                'extra_value' => '',
            ],
            [
                'id' => 5,
                'type' => BaseinfoTypesEnum::DISCIPLINE->value,
                'value' => 'Electricity',
                // 'value' => 'برق',
                'priority' => 0,
                'parent_id' => 1,
                'user_can_add' => 0,
                'user_can_view' => 1,
                'extra_value' => '',
            ],
            [
                'id' => 6,
                'type' => BaseinfoTypesEnum::DISCIPLINE->value,
                'value' => 'Architecture',
                // 'value' => 'معماری',
                'priority' => 0,
                'parent_id' => 1,
                'user_can_add' => 0,
                'user_can_view' => 1,
                'extra_value' => '',
            ],
            [
                'id' => 7,
                'type' => BaseinfoTypesEnum::UNIT_MEASURE->value,
                'value' => 'Unit Of Measure',
                'priority' => 0,
                'parent_id' => 0,
                'user_can_add' => 0,
                'user_can_view' => 0,
                'extra_value' => '',
            ],
            [
                'id' => 8,
                'type' => BaseinfoTypesEnum::UNIT_MEASURE->value,
                'value' => 'Count',
                // 'value' => 'عدد',
                'priority' => 0,
                'parent_id' => 7,
                'user_can_add' => 0,
                'user_can_view' => 0,
                'extra_value' => '',
            ],
            [
                'id' => 9,
                'type' => BaseinfoTypesEnum::UNIT_MEASURE->value,
                'value' => 'Kilo Gram',
                // 'value' => 'کیلو گرم',
                'priority' => 0,
                'parent_id' => 7,
                'user_can_add' => 0,
                'user_can_view' => 0,
                'extra_value' => '',
            ],
            [
                'id' => 10,
                'type' => BaseinfoTypesEnum::UNIT_MEASURE->value,
                'value' => 'Meter (length)',
                // 'value' => 'متر (طول)',
                'priority' => 0,
                'parent_id' => 7,
                'user_can_add' => 0,
                'user_can_view' => 0,
                'extra_value' => '',
            ],
            [
                'id' => 11,
                'type' => BaseinfoTypesEnum::UNIT_MEASURE->value,
                'value' => 'Cubic Meter',
                // 'value' => 'متر مکعب',
                'priority' => 0,
                'parent_id' => 7,
                'user_can_add' => 0,
                'user_can_view' => 0,
                'extra_value' => '',
            ],
            [
                'id' => 12,
                'type' => BaseinfoTypesEnum::UNIT_MEASURE->value,
                'value' => 'Square meters',
                // 'value' => 'متر مربع',
                'priority' => 0,
                'parent_id' => 7,
                'user_can_add' => 0,
                'user_can_view' => 0,
                'extra_value' => '',
            ],
            [
                'id' => 13,
                'type' => 'money_unit',
                'value' => 'واحد پول',
                'priority' => 0,
                'parent_id' => 0,
                'user_can_add' => 0,
                'user_can_view' => 1,
                'extra_value' => '',
            ],

            [
                'id' => 15,
                'type' => 'money_unit',
                'value' => 'یورو',
                'priority' => 2,
                'parent_id' => 13,
                'user_can_add' => 0,
                'user_can_view' => 1,
                'extra_value' => '',
            ],
            [
                'id' => 16,
                'type' => 'typeAttachment',
                'value' => 'نوع فایل آپلودی',
                'priority' => 0,
                'parent_id' => 0,
                'user_can_add' => 0,
                'user_can_view' => 1,
                'extra_value' => '',
            ],
            [
                'id' => 17,
                'type' => 'typeAttachment',
                'value' => 'MRS',
                'priority' => 0,
                'parent_id' => 16,
                'user_can_add' => 0,
                'user_can_view' => 1,
                'extra_value' => '',
            ],
            [
                'id' => 18,
                'type' => 'typeAttachment',
                'value' => 'MIV',
                'priority' => 0,
                'parent_id' => 16,
                'user_can_add' => 0,
                'user_can_view' => 1,
                'extra_value' => '',
            ],
            [
                'id' => 19,
                'type' => 'typeAttachment',
                'value' => 'MRV',
                'priority' => 0,
                'parent_id' => 16,
                'user_can_add' => 0,
                'user_can_view' => 1,
                'extra_value' => '',
            ],
            [
                'id' => 20,
                'type' => 'typeAttachment',
                'value' => 'فاکتور',
                'priority' => 0,
                'parent_id' => 16,
                'user_can_add' => 0,
                'user_can_view' => 1,
                'extra_value' => '',
            ],
            [
                'id' => 21,
                'type' => BaseinfoTypesEnum::UNIT_MEASURE->value,
                'value' => 'Litre',
                // 'value' => 'لیتر',
                'priority' => 0,
                'parent_id' => 7,
                'user_can_add' => 0,
                'user_can_view' => 0,
                'extra_value' => '',
            ],
            [
                'id' => 22,
                'type' => BaseinfoTypesEnum::UNIT_MEASURE->value,
                'value' => 'Inch',
                // 'value' => 'اینچ',
                'priority' => 0,
                'parent_id' => 7,
                'user_can_add' => 0,
                'user_can_view' => 0,
                'extra_value' => '',
            ],
            [
                'id' => 23,
                'type' => BaseinfoTypesEnum::UNIT_MEASURE->value,
                'value' => 'Paper',
                // 'value' => 'برگ',
                'priority' => 0,
                'parent_id' => 7,
                'user_can_add' => 0,
                'user_can_view' => 0,
                'extra_value' => '',
            ],

            [
                'id' => 25,
                'type' => BaseinfoTypesEnum::UNIT_MEASURE->value,
                'value' => 'Collection',
                // 'value' => 'مجموعه',
                'priority' => 0,
                'parent_id' => 7,
                'user_can_add' => 0,
                'user_can_view' => 0,
                'extra_value' => '',
            ],
            [
                'id' => 26,
                'type' => BaseinfoTypesEnum::UNIT_MEASURE->value,
                'value' => 'Packet',
                // 'value' => 'بسته',
                'priority' => 0,
                'parent_id' => 7,
                'user_can_add' => 0,
                'user_can_view' => 0,
                'extra_value' => '',
            ],
            [
                'id' => 27,
                'type' => BaseinfoTypesEnum::UNIT_MEASURE->value,
                'value' => 'Branch',
                // 'value' => 'شاخه',
                'priority' => 0,
                'parent_id' => 7,
                'user_can_add' => 0,
                'user_can_view' => 0,
                'extra_value' => '',
            ],

            [
                'id' => 28,
                'type' => BaseinfoTypesEnum::UNIT_MEASURE->value,
                'value' => 'Gallon',
                // 'value' => 'گالن',
                'priority' => 0,
                'parent_id' => 7,
                'user_can_add' => 0,
                'user_can_view' => 0,
                'extra_value' => '',
            ],
            [
                'id' => 29,
                'type' => BaseinfoTypesEnum::UNIT_MEASURE->value,
                'value' => 'Bucket',
                // 'value' => 'سطل',
                'priority' => 0,
                'parent_id' => 7,
                'user_can_add' => 0,
                'user_can_view' => 0,
                'extra_value' => '',
            ],
            [
                'id' => 30,
                'type' => BaseinfoTypesEnum::UNIT_MEASURE->value,
                'value' => 'Square meters',
                // 'value' => 'متر مربع',
                'priority' => 0,
                'parent_id' => 7,
                'user_can_add' => 0,
                'user_can_view' => 0,
                'extra_value' => '',
            ],
            [
                'id' => 31,
                'type' => BaseinfoTypesEnum::UNIT_MEASURE->value,
                'value' => 'Can',
                // 'value' => 'قوطی',
                'priority' => 0,
                'parent_id' => 7,
                'user_can_add' => 0,
                'user_can_view' => 0,
                'extra_value' => '',
            ],
            [
                'id' => 32,
                'type' => BaseinfoTypesEnum::UNIT_MEASURE->value,
                'value' => 'Carton',
                // 'value' => 'کارتن',
                'priority' => 0,
                'parent_id' => 7,
                'user_can_add' => 0,
                'user_can_view' => 0,
                'extra_value' => '',
            ],
            [
                'id' => 33,
                'type' => BaseinfoTypesEnum::UNIT_MEASURE->value,
                'value' => 'Bag',
                // 'value' => 'کیسه',
                'priority' => 0,
                'parent_id' => 7,
                'user_can_add' => 0,
                'user_can_view' => 0,
                'extra_value' => '',
            ],
            [
                'id' => 34,
                'type' => BaseinfoTypesEnum::UNIT_MEASURE->value,
                'value' => 'Equipment',
                // 'value' => 'دستگاه',
                'priority' => 0,
                'parent_id' => 7,
                'user_can_add' => 0,
                'user_can_view' => 0,
                'extra_value' => '',
            ],
            [
                'id' => 35,
                'type' => BaseinfoTypesEnum::UNIT_MEASURE->value,
                'value' => 'Role',
                // 'value' => 'رول',
                'priority' => 0,
                'parent_id' => 7,
                'user_can_add' => 0,
                'user_can_view' => 0,
                'extra_value' => '',
            ],
            [
                'id' => 36,
                'type' => BaseinfoTypesEnum::UNIT_MEASURE->value,
                'value' => 'String',
                // 'value' => 'رشته',
                'priority' => 0,
                'parent_id' => 7,
                'user_can_add' => 0,
                'user_can_view' => 0,
                'extra_value' => '',
            ],
            [
                'id' => 38,
                'type' => BaseinfoTypesEnum::UNIT_MEASURE->value,
                'value' => 'sphere',
                // 'value' => 'توپ',
                'priority' => 0,
                'parent_id' => 7,
                'user_can_add' => 0,
                'user_can_view' => 0,
                'extra_value' => '',
            ],
            [
                'id' => 39,
                'type' => BaseinfoTypesEnum::UNIT_MEASURE->value,
                'value' => 'Pairs',
                // 'value' => 'جفت',
                'priority' => 0,
                'parent_id' => 7,
                'user_can_add' => 0,
                'user_can_view' => 0,
                'extra_value' => '',
            ],
            [
                'id' => 40,
                'type' => BaseinfoTypesEnum::UNIT_MEASURE->value,
                'value' => 'Hoop',
                // 'value' => 'حلقه',
                'priority' => 0,
                'parent_id' => 7,
                'user_can_add' => 0,
                'user_can_view' => 0,
                'extra_value' => '',
            ],
            [
                'id' => 41,
                'type' => BaseinfoTypesEnum::UNIT_MEASURE->value,
                'value' => 'Category',
                // 'value' => 'دست',
                'priority' => 0,
                'parent_id' => 7,
                'user_can_add' => 0,
                'user_can_view' => 0,
                'extra_value' => '',
            ],
            [
                'id' => 42,
                'type' => BaseinfoTypesEnum::UNIT_MEASURE->value,
                'value' => 'Cell',
                // 'value' => 'سلول',
                'priority' => 0,
                'parent_id' => 7,
                'user_can_add' => 0,
                'user_can_view' => 0,
                'extra_value' => '',
            ],
            [
                'id' => 43,
                'type' => BaseinfoTypesEnum::UNIT_MEASURE->value,
                'value' => 'Barrel',
                // 'value' => 'بشکه',
                'priority' => 0,
                'parent_id' => 7,
                'user_can_add' => 0,
                'user_can_view' => 0,
                'extra_value' => '',
            ],
            [
                'id' => 45,
                'type' => 'money_unit',
                'value' => 'ریال',
                'priority' => 1,
                'parent_id' => 13,
                'user_can_add' => 0,
                'user_can_view' => 1,
                'extra_value' => '',
            ],
            [
                'id' => 46,
                'type' => 'defaultId',
                'value' => '---',
                'priority' => 0,
                'parent_id' => 0,
                'user_can_add' => 0,
                'user_can_view' => 0,
                'extra_value' => '',
            ],
            [
                'id' => 47,
                'type' => 'unit_requester',
                'value' => 'واحد درخواست کننده',
                'priority' => 0,
                'parent_id' => 0,
                'user_can_add' => 0,
                'user_can_view' => 0,
                'extra_value' => '',
            ],
            [
                'id' => 48,
                'type' => 'unit_requester',
                'value' => 'مدیریت' . ' ( 100 ) ',
                'priority' => 0,
                'parent_id' => 47,
                'user_can_add' => 0,
                'user_can_view' => 0,
                'extra_value' => json_encode([
                    'code' => '100',
                ]),
            ],
            [
                'id' => 49,
                'type' => 'unit_requester',
                'value' => 'امور قرارداد ها و امور پیمان' . ' ( 101 ) ',
                'priority' => 0,
                'parent_id' => 47,
                'user_can_add' => 0,
                'user_can_view' => 0,
                'extra_value' => json_encode([
                    'code' => '101',
                ]),
            ],
            [
                'id' => 50,
                'type' => 'unit_requester',
                'value' => 'روابط عمومی' . ' ( 102 ) ',
                'priority' => 0,
                'parent_id' => 47,
                'user_can_add' => 0,
                'user_can_view' => 0,
                'extra_value' => json_encode([
                    'code' => '102',
                ]),
            ],
            [
                'id' => 51,
                'type' => 'unit_requester',
                'value' => 'بازار یابی مناقصات' . ' ( 103 ) ',
                'priority' => 0,
                'parent_id' => 47,
                'user_can_add' => 0,
                'user_can_view' => 0,
                'extra_value' => json_encode([
                    'code' => '103',
                ]),
            ],
            [
                'id' => 52,
                'type' => 'unit_requester',
                'value' => 'کنترل و تضمین کیفیت' . ' ( 104 ) ',
                'priority' => 0,
                'parent_id' => 47,
                'user_can_add' => 0,
                'user_can_view' => 0,
                'extra_value' => json_encode([
                    'code' => '104',
                ]),
            ],
            [
                'id' => 53,
                'type' => 'unit_requester',
                'value' => 'برنامه ریزی و کنترل پروژه' . ' ( 105 ) ',
                'priority' => 0,
                'parent_id' => 47,
                'user_can_add' => 0,
                'user_can_view' => 0,
                'extra_value' => json_encode([
                    'code' => '105',
                ]),
            ],
            [
                'id' => 54,
                'type' => 'unit_requester',
                'value' => 'فنی مهندسی' . ' ( 106 ) ',
                'priority' => 0,
                'parent_id' => 47,
                'user_can_add' => 0,
                'user_can_view' => 0,
                'extra_value' => json_encode([
                    'code' => '106',
                ]),
            ],
            [
                'id' => 56,
                'type' => 'unit_requester',
                'value' => 'الکتریکال' . ' ( 107 ) ',
                'priority' => 0,
                'parent_id' => 47,
                'user_can_add' => 0,
                'user_can_view' => 0,
                'extra_value' => json_encode([
                    'code' => '107',
                ]),
            ],
            [
                'id' => 57,
                'type' => 'unit_requester',
                'value' => 'ابزار دقیق' . ' ( 108 ) ',
                'priority' => 0,
                'parent_id' => 47,
                'user_can_add' => 0,
                'user_can_view' => 0,
                'extra_value' => json_encode([
                    'code' => '108',
                ]),
            ],
            [
                'id' => 58,
                'type' => 'unit_requester',
                'value' => 'سیویل - ص' . ' ( 109 ) ',
                'priority' => 0,
                'parent_id' => 47,
                'user_can_add' => 0,
                'user_can_view' => 0,
                'extra_value' => json_encode([
                    'code' => '109',
                ]),
            ],
            [
                'id' => 59,
                'type' => 'unit_requester',
                'value' => 'مکانیکال' . ' ( 110 ) ',
                'priority' => 0,
                'parent_id' => 47,
                'user_can_add' => 0,
                'user_can_view' => 0,
                'extra_value' => json_encode([
                    'code' => '110',
                ]),
            ],
            [
                'id' => 60,
                'type' => 'unit_requester',
                'value' => 'تامین تجهیزات داخلی' . ' ( 111 ) ',
                'priority' => 0,
                'parent_id' => 47,
                'user_can_add' => 0,
                'user_can_view' => 0,
                'extra_value' => json_encode([
                    'code' => '111',
                ]),
            ],
            [
                'id' => 61,
                'type' => 'unit_requester',
                'value' => 'تامین تجهیزات خارجی' . ' ( 112 ) ',
                'priority' => 0,
                'parent_id' => 47,
                'user_can_add' => 0,
                'user_can_view' => 0,
                'extra_value' => json_encode([
                    'code' => '112',
                ]),
            ],
            [
                'id' => 62,
                'type' => 'unit_requester',
                'value' => 'برش' . ' ( 113 ) ',
                'priority' => 0,
                'parent_id' => 47,
                'user_can_add' => 0,
                'user_can_view' => 0,
                'extra_value' => json_encode([
                    'code' => '113',
                ]),
            ],
            [
                'id' => 63,
                'type' => 'unit_requester',
                'value' => 'ساخت' . ' ( 114 ) ',
                'priority' => 0,
                'parent_id' => 47,
                'user_can_add' => 0,
                'user_can_view' => 0,
                'extra_value' => json_encode([
                    'code' => '114',
                ]),
            ],
            [
                'id' => 64,
                'type' => 'unit_requester',
                'value' => 'دفتر فنی' . ' ( 115 ) ',
                'priority' => 0,
                'parent_id' => 47,
                'user_can_add' => 0,
                'user_can_view' => 0,
                'extra_value' => json_encode([
                    'code' => '115',
                ]),
            ],
            [
                'id' => 65,
                'type' => 'unit_requester',
                'value' => 'مصرفی انبار خرید تهران ' . ' ( 116 ) ',
                'priority' => 0,
                'parent_id' => 47,
                'user_can_add' => 0,
                'user_can_view' => 0,
                'extra_value' => json_encode([
                    'code' => '116',
                ]),
            ],
            [
                'id' => 66,
                'type' => 'unit_requester',
                'value' => 'مالی' . ' ( 117 ) ',
                'priority' => 0,
                'parent_id' => 47,
                'user_can_add' => 0,
                'user_can_view' => 0,
                'extra_value' => json_encode([
                    'code' => '117',
                ]),
            ],
            [
                'id' => 67,
                'type' => 'unit_requester',
                'value' => 'اداری' . ' ( 118 ) ',
                'priority' => 0,
                'parent_id' => 47,
                'user_can_add' => 0,
                'user_can_view' => 0,
                'extra_value' => json_encode([
                    'code' => '118',
                ]),
            ],
            [
                'id' => 68,
                'type' => 'unit_requester',
                'value' => 'پشتیبانی' . ' ( 119 ) ',
                'priority' => 0,
                'parent_id' => 47,
                'user_can_add' => 0,
                'user_can_view' => 0,
                'extra_value' => json_encode([
                    'code' => '119',
                ]),
            ],
            [
                'id' => 69,
                'type' => 'unit_requester',
                'value' => 'خدماتی' . ' ( 120 ) ',
                'priority' => 0,
                'parent_id' => 47,
                'user_can_add' => 0,
                'user_can_view' => 0,
                'extra_value' => json_encode([
                    'code' => '120',
                ]),
            ],
            [
                'id' => 70,
                'type' => 'unit_requester',
                'value' => 'IT' . ' ( 121 ) ',
                'priority' => 0,
                'parent_id' => 47,
                'user_can_add' => 0,
                'user_can_view' => 0,
                'extra_value' => json_encode([
                    'code' => '121',
                ]),
            ],
            [
                'id' => 71,
                'type' => 'unit_requester',
                'value' => 'تخصصی مالی' . ' ( 122 ) ',
                'priority' => 0,
                'parent_id' => 47,
                'user_can_add' => 0,
                'user_can_view' => 0,
                'extra_value' => json_encode([
                    'code' => '122',
                ]),
            ],
            [
                'id' => 72,
                'type' => 'unit_requester',
                'value' => 'سازه' . ' ( 123 ) ',
                'priority' => 0,
                'parent_id' => 47,
                'user_can_add' => 0,
                'user_can_view' => 0,
                'extra_value' => json_encode([
                    'code' => '123',
                ]),
            ],
            [
                'id' => 73,
                'type' => 'unit_requester',
                'value' => 'نصب' . ' ( 124 ) ',
                'priority' => 0,
                'parent_id' => 47,
                'user_can_add' => 0,
                'user_can_view' => 0,
                'extra_value' => json_encode([
                    'code' => '124',
                ]),
            ],
            [
                'id' => 74,
                'type' => 'unit_requester',
                'value' => 'سیویل - غ' . ' ( 125 ) ',
                'priority' => 0,
                'parent_id' => 47,
                'user_can_add' => 0,
                'user_can_view' => 0,
                'extra_value' => json_encode([
                    'code' => '125',
                ]),
            ],
            [
                'id' => 75,
                'type' => 'unit_requester',
                'value' => 'ماشین آلات و تجهیزات تولید' . ' ( 126 ) ',
                'priority' => 0,
                'parent_id' => 47,
                'user_can_add' => 0,
                'user_can_view' => 0,
                'extra_value' => json_encode([
                    'code' => '126',
                ]),
            ],
            [
                'id' => 76,
                'type' => 'unit_requester',
                'value' => 'ماشین آلات' . ' ( 127 ) ',
                'priority' => 0,
                'parent_id' => 47,
                'user_can_add' => 0,
                'user_can_view' => 0,
                'extra_value' => json_encode([
                    'code' => '127',
                ]),
            ],
            [
                'id' => 77,
                'type' => 'unit_requester',
                'value' => 'قطعات یدکی راه‌اندازی' . ' ( 128 ) ',
                'priority' => 0,
                'parent_id' => 47,
                'user_can_add' => 0,
                'user_can_view' => 0,
                'extra_value' => json_encode([
                    'code' => '128',
                ]),
            ],
            [
                'id' => 78,
                'type' => 'typeAttachment',
                'value' => 'مدارک فنی',
                'priority' => 0,
                'parent_id' => 16,
                'user_can_add' => 0,
                'user_can_view' => 1,
                'extra_value' => '',
            ],
            [
                'id' => 79,
                'type' => 'unit_requester',
                'value' => 'مصرفی انبار سایت ' . ' ( 200 ) ',
                'priority' => 0,
                'parent_id' => 47,
                'user_can_add' => 0,
                'user_can_view' => 0,
                'extra_value' => json_encode([
                    'code' => '200',
                ]),
            ],
            [
                'id' => 80,
                'type' => BaseinfoTypesEnum::DISCIPLINE->value,
                'value' => 'Mechanical',
                // 'value' => 'مکانیکال',
                'priority' => 0,
                'parent_id' => 1,
                'user_can_add' => 0,
                'user_can_view' => 1,
                'extra_value' => '',
            ],
            [
                'id' => 81,
                'type' => BaseinfoTypesEnum::DISCIPLINE->value,
                'value' => 'Piping',
                // 'value' => 'پایپینگ',
                'priority' => 0,
                'parent_id' => 1,
                'user_can_add' => 0,
                'user_can_view' => 1,
                'extra_value' => '',
            ],
            [
                'id' => 82,
                'type' => BaseinfoTypesEnum::REQUEST_STATUS->value,
                'value' => 'Request Status',
                'priority' => 0,
                'parent_id' => 0,
                'user_can_add' => 0,
                'user_can_view' => 1,
                'extra_value' => '',
            ],
            [
                'id' => 83,
                'type' => BaseinfoTypesEnum::REQUEST_STATUS->value,
                'value' => 'Sent',
                'priority' => 1,
                'parent_id' => 82,
                'user_can_add' => 0,
                'user_can_view' => 1,
                'extra_value' => '',
            ],
            [
                'id' => 84,
                'type' => BaseinfoTypesEnum::REQUEST_STATUS->value,
                'value' => 'Accept',
                'priority' => 3,
                'parent_id' => 82,
                'user_can_add' => 0,
                'user_can_view' => 1,
                'extra_value' => '',
            ],
            [
                'id' => 86,
                'type' => BaseinfoTypesEnum::REQUEST_STATUS->value,
                'value' => 'Financial',
                'priority' => 4,
                'parent_id' => 82,
                'user_can_add' => 0,
                'user_can_view' => 1,
                'extra_value' => '',
            ],
            [
                'id' => 88,
                'type' => BaseinfoTypesEnum::REQUEST_STATUS->value,
                'value' => 'Reject',
                'priority' => 5,
                'parent_id' => 83,
                'user_can_add' => 0,
                'user_can_view' => 1,
                'extra_value' => '',
            ],
            [
                'id' => 89,
                'type' => BaseinfoTypesEnum::REQUEST_STATUS->value,
                'value' => 'Block',
                'priority' => 6,
                'parent_id' => 83,
                'user_can_add' => 0,
                'user_can_view' => 1,
                'extra_value' => '',
            ],
            [
                'id' => 90,
                'type' => BaseinfoTypesEnum::REQUEST_TYPE->value,
                'value' => 'Type Request',
                'priority' => 0,
                'parent_id' => 0,
                'user_can_add' => 0,
                'user_can_view' => 1,
                'extra_value' => '',
            ],
            [
                'id' => 91,
                'type' => BaseinfoTypesEnum::REQUEST_TYPE->value,
                'value' => 'Supply In',
                'priority' => 0,
                'parent_id' => 90,
                'user_can_add' => 0,
                'user_can_view' => 1,
                'extra_value' => '',
            ],
            [
                'id' => 92,
                'type' => BaseinfoTypesEnum::REQUEST_TYPE->value,
                'value' => 'Supply',
                'priority' => 0,
                'parent_id' => 90,
                'user_can_add' => 0,
                'user_can_view' => 1,
                'extra_value' => '',
            ],
            [
                'id' => 93,
                'type' => BaseinfoTypesEnum::REQUEST_TYPE->value,
                'value' => 'Supplied Before',
                'priority' => 0,
                'parent_id' => 90,
                'user_can_add' => 0,
                'user_can_view' => 1,
                'extra_value' => json_encode([
                    'color' => '#ffrfrfr',
                ]),
            ],
            [
                'id' => 94,
                'type' => BaseinfoTypesEnum::REQUEST_STATUS->value,
                'value' => 'Assign To Buyer',
                'priority' => 6,
                'parent_id' => 83,
                'user_can_add' => 0,
                'user_can_view' => 1,
                'extra_value' => '',
            ],
            [
                'id' => 95,
                'type' => BaseinfoTypesEnum::REQUEST_STATUS->value,
                'value' => 'Supply',
                'priority' => 7,
                'parent_id' => 83,
                'user_can_add' => 0,
                'user_can_view' => 1,
                'extra_value' => '',
            ],
            [
                'id' => 96,
                'type' => BaseinfoTypesEnum::UNIT_MEASURE->value,
                'value' => 'Palette',
                // 'value' => 'پالت',
                'priority' => 0,
                'parent_id' => 7,
                'user_can_add' => 0,
                'user_can_view' => 0,
                'extra_value' => '',
            ],
            [
                'id' => 97,
                'type' => BaseinfoTypesEnum::REQUEST_STATUS->value,
                'value' => 'Incomplete supply',
                'priority' => 8,
                'parent_id' => 82,
                'user_can_add' => 0,
                'user_can_view' => 1,
                'extra_value' => json_encode([
                    'color' => '#e6e600',
                    'status' => '',
                    'permission' => 'supply-unfinished',
                ]),
            ],
            [
                'id' => 98,
                'type' => 'personality',
                'value' => 'نوع شخصیت',
                'priority' => 0,
                'parent_id' => 0,
                'user_can_add' => 0,
                'user_can_view' => 1,
                'extra_value' => '',
            ],
            [
                'id' => 99,
                'type' => 'personality',
                'value' => 'کاربر سامانه',
                'priority' => 0,
                'parent_id' => 98,
                'user_can_add' => 0,
                'user_can_view' => 1,
                'extra_value' => '',
            ],
            [
                'id' => 100,
                'type' => 'personality',
                'value' => 'عادی',
                'priority' => 0,
                'parent_id' => 98,
                'user_can_add' => 0,
                'user_can_view' => 1,
                'extra_value' => '',
            ],
            [
                'id' => 101,
                'type' => 'condition_category',
                'value' => 'وضعیت کالا در انبار',
                'priority' => 0,
                'parent_id' => 0,
                'user_can_add' => 0,
                'user_can_view' => 1,
                'extra_value' => '',
            ],
            [
                'id' => 102,
                'type' => 'condition_category',
                'value' => 'سالم',
                'priority' => 0,
                'parent_id' => 101,
                'user_can_add' => 0,
                'user_can_view' => 1,
                'extra_value' => '',
            ],
            [
                'id' => 103,
                'type' => 'condition_category',
                'value' => 'اسقاط',
                'priority' => 0,
                'parent_id' => 101,
                'user_can_add' => 0,
                'user_can_view' => 1,
                'extra_value' => '',
            ],
            [
                'id' => 104,
                'type' => 'condition_category',
                'value' => 'خسارت دیده',
                'priority' => 0,
                'parent_id' => 101,
                'user_can_add' => 0,
                'user_can_view' => 1,
                'extra_value' => '',
            ],
            [
                'id' => 105,
                'type' => 'album_image',
                'value' => 'آلبوم عکس',
                'priority' => 0,
                'parent_id' => 0,
                'user_can_add' => 0,
                'user_can_view' => 1,
                'extra_value' => '',
            ],
            [
                'id' => 106,
                'type' => 'category-person',
                'value' => 'دسته بندی اشخاص',
                'priority' => 0,
                'parent_id' => 0,
                'user_can_add' => 0,
                'user_can_view' => 1,
                'extra_value' => '',
            ],
            [
                'id' => 108,
                'type' => 'request_type_observe',
                'value' => 'ثبت درخواست',
                'priority' => 0,
                'parent_id' => 107,
                'user_can_add' => 0,
                'user_can_view' => 1,
                'extra_value' => '',
            ],
            [
                'id' => 109,
                'type' => 'request_type_observe',
                'value' => 'ویرایش درخواست',
                'priority' => 0,
                'parent_id' => 107,
                'user_can_add' => 0,
                'user_can_view' => 1,
                'extra_value' => '',
            ],
            [
                'id' => 110,
                'type' => BaseinfoTypesEnum::REQUEST_STATUS->value,
                'value' => 'Accept Financial',
                'priority' => 2,
                'parent_id' => 82,
                'user_can_add' => 0,
                'user_can_view' => 1,
                'extra_value' => '',
            ],
            [
                'id' => 111,
                'type' => 'typeAttachment',
                'value' => 'برگ رسید',
                'priority' => 0,
                'parent_id' => 16,
                'user_can_add' => 0,
                'user_can_view' => 1,
                'extra_value' => '',
            ],
            [
                'id' => 112,
                'type' => 'typeAttachment',
                'value' => 'رسید انبار',
                'priority' => 0,
                'parent_id' => 16,
                'user_can_add' => 0,
                'user_can_view' => 1,
                'extra_value' => '',
            ],
            [
                'id' => 113,
                'type' => 'project_request',
                'value' => 'پروژه ی درخواست',
                'priority' => 0,
                'parent_id' => 0,
                'user_can_add' => 0,
                'user_can_view' => 1,
                'extra_value' => '',
            ],
            [
                'id' => 114,
                'type' => 'project_request',
                'value' => 'بافق کسری یزد',
                'priority' => 0,
                'parent_id' => 113,
                'user_can_add' => 0,
                'user_can_view' => 1,
                'extra_value' => '',
            ],
            [
                'id' => 115,
                'type' => 'project_request',
                'value' => 'بهره برداری کارخانه گندله سازی اپال پارسیان سنگان',
                'priority' => 0,
                'parent_id' => 113,
                'user_can_add' => 0,
                'user_can_view' => 1,
                'extra_value' => '',
            ],
            [
                'id' => 116,
                'type' => 'project_request',
                'value' => 'اجرای کارخانه ی کنسانتره به ظرفیت 2.4 میلیون تن',
                'priority' => 0,
                'parent_id' => 113,
                'user_can_add' => 0,
                'user_can_view' => 1,
                'extra_value' => '',
            ],
            [
                'id' => 117,
                'type' => 'project_request',
                'value' => 'مپنا',
                'priority' => 0,
                'parent_id' => 113,
                'user_can_add' => 0,
                'user_can_view' => 1,
                'extra_value' => '',
            ],
            [
                'id' => 118,
                'type' => 'project_request',
                'value' => 'دانیلی',
                'priority' => 0,
                'parent_id' => 113,
                'user_can_add' => 0,
                'user_can_view' => 1,
                'extra_value' => '',
            ],
            [
                'id' => 119,
                'type' => 'project_request',
                'value' => 'متفرقه',
                'priority' => 0,
                'parent_id' => 113,
                'user_can_add' => 0,
                'user_can_view' => 1,
                'extra_value' => '',
            ],
            [
                'id' => 120,
                'type' => BaseinfoTypesEnum::REQUEST_STATUS->value,
                'value' => 'First accept',
                'priority' => 2,
                'parent_id' => 82,
                'user_can_add' => 0,
                'user_can_view' => 1,
                'extra_value' => '',
            ],
            [
                'id' => 121,
                'type' => 'unit_import_excel',
                'value' => 'واحد برای کالاهایی اکسلی',
                'priority' => 2,
                'parent_id' => 0,
                'user_can_add' => 0,
                'user_can_view' => 1,
                'extra_value' => '',
            ],
            [
                'id' => 122,
                'type' => 'contract_type',
                'value' => '',
                'priority' => 0,
                'parent_id' => 0,
                'user_can_add' => 0,
                'user_can_view' => 1,
                'extra_value' => '',
            ],
            [
                'id' => 123,
                'type' => 'job_title',
                'value' => '',
                'priority' => 0,
                'parent_id' => 0,
                'user_can_add' => 0,
                'user_can_view' => 1,
                'extra_value' => '',
            ],
            [
                'id' => 124,
                'type' => 'month',
                'value' => 'ماه های سال',
                'priority' => 0,
                'parent_id' => 0,
                'user_can_add' => 0,
                'user_can_view' => 1,
                'extra_value' => '',
            ],
            [
                'id' => 125,
                'type' => 'month',
                'value' => 'فروردین',
                'priority' => 0,
                'parent_id' => 124,
                'user_can_add' => 0,
                'user_can_view' => 1,
                'extra_value' => '',
            ],
            [
                'id' => 126,
                'type' => 'month',
                'value' => 'اردیبهشت',
                'priority' => 0,
                'parent_id' => 124,
                'user_can_add' => 0,
                'user_can_view' => 1,
                'extra_value' => '',
            ],
            [
                'id' => 127,
                'type' => 'month',
                'value' => 'خرداد',
                'priority' => 0,
                'parent_id' => 124,
                'user_can_add' => 0,
                'user_can_view' => 1,
                'extra_value' => '',
            ],
            [
                'id' => 128,
                'type' => 'month',
                'value' => 'تیر',
                'priority' => 0,
                'parent_id' => 124,
                'user_can_add' => 0,
                'user_can_view' => 1,
                'extra_value' => '',
            ],
            [
                'id' => 129,
                'type' => 'month',
                'value' => 'مرداد',
                'priority' => 0,
                'parent_id' => 124,
                'user_can_add' => 0,
                'user_can_view' => 1,
                'extra_value' => '',
            ],
            [
                'id' => 130,
                'type' => 'month',
                'value' => 'شهریور',
                'priority' => 0,
                'parent_id' => 124,
                'user_can_add' => 0,
                'user_can_view' => 1,
                'extra_value' => '',
            ],
            [
                'id' => 131,
                'type' => 'month',
                'value' => 'مهر',
                'priority' => 0,
                'parent_id' => 124,
                'user_can_add' => 0,
                'user_can_view' => 1,
                'extra_value' => '',
            ],
            [
                'id' => 132,
                'type' => 'month',
                'value' => 'آبان',
                'priority' => 0,
                'parent_id' => 124,
                'user_can_add' => 0,
                'user_can_view' => 1,
                'extra_value' => '',
            ],
            [
                'id' => 133,
                'type' => 'month',
                'value' => 'آذر',
                'priority' => 0,
                'parent_id' => 124,
                'user_can_add' => 0,
                'user_can_view' => 1,
                'extra_value' => '',
            ],
            [
                'id' => 134,
                'type' => 'month',
                'value' => 'دی',
                'priority' => 0,
                'parent_id' => 124,
                'user_can_add' => 0,
                'user_can_view' => 1,
                'extra_value' => '',
            ],
            [
                'id' => 135,
                'type' => 'month',
                'value' => 'بهمن',
                'priority' => 0,
                'parent_id' => 124,
                'user_can_add' => 0,
                'user_can_view' => 1,
                'extra_value' => '',
            ],
            [
                'id' => 136,
                'type' => 'month',
                'value' => 'اسفند',
                'priority' => 0,
                'parent_id' => 124,
                'user_can_add' => 0,
                'user_can_view' => 1,
                'extra_value' => '',
            ],
            [
                'id' => 137,
                'type' => 'project_request',
                'value' => 'کارخانه احیا سنگ آهن مرکزی',
                'priority' => 0,
                'parent_id' => 113,
                'user_can_add' => 0,
                'user_can_view' => 1,
                'extra_value' => '',
            ],
            [
                'id' => 138,
                'type' => 'project_request',
                'value' => 'تدبیر صنعت قرن',
                'priority' => 0,
                'parent_id' => 113,
                'user_can_add' => 0,
                'user_can_view' => 1,
                'extra_value' => '',
            ],
            [
                'id' => 139,
                'type' => 'project_request',
                'value' => 'احداث کنسانتره گلالی دو میلیون تن',
                'priority' => 0,
                'parent_id' => 113,
                'user_can_add' => 0,
                'user_can_view' => 1,
                'extra_value' => '',
            ],
        ]);
        DB::unprepared('SET FOREIGN_KEY_CHECKS=1;');
        DB::unprepared('ALTER TABLE baseinfos AUTO_INCREMENT = 10000');
    }
}
